import Head from "next/head";
import Image from "next/Image";
import Image1 from "../components/assets/header-img.jpg"
import Image2 from "../components/assets/header-text-img.jpg"
import Image3 from "../components/assets/header-hamburguer-img.jpg"


const Header = (props: any) => {

    return (
        <>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon-shushibar.ico" />
            </Head>
            <div className="relative rounded-3xl p-2">
                <Image
                    src={Image3}
                    alt="hamburguer"
                    height={20}
                    width={30}
                    className="z-20 absolute top-0 left-0"
                />
                <Image
                    src={Image1}
                    alt="image"
                    objectFit="fill"
                    className="z-10 relative top-0 left-0 rounded-3xl"
                />
                <Image
                    src={Image2}
                    alt="text"
                    objectFit="fill"
                    className="z-30 relative"
                />
            </div>
        </>
    );
};

export default Header;