import type { GetStaticProps, NextPage } from "next";
import { InferGetStaticPropsType } from "next";
import Head from "next/head";
import Link from 'next/link';

import { getProducts } from "../services/Supabase/Products";
import { getCategories } from "../services/Supabase/Categories";
import { useMemo, useState } from "react";

import ListItem from "../layouts/ListItem";
import ProductOptionSelected from "../components/ProductOptionSelected"

const Bebidas: NextPage = (
  props: InferGetStaticPropsType<typeof getStaticProps>
) => {
  const [currentSelectedCategory, setCurrentSelectedCategory] = useState(
    props?.categories[0]?.id
  );

  const productsFiltered = useMemo(
    () =>
      props.products.filter(
        (product: any) => product.category_id === currentSelectedCategory
      ),
    [props.products, currentSelectedCategory]
  );

  console.log("cardapio", {
    productsUnfiltered: props.products,
    productsFiltered,
    currentSelectedCategory,
  });

  return (
    <>
      <Head>
        <title>Bebidas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-shushibar.ico" />
      </Head>
      <main className="min-h-screen bg-gray-200 pt-3 justify-center items-center pb-3">
        <div className="w-full">
          <div className="bg-gray-400 w-8 h-1 rounded mx-auto"></div>
        </div>
        <div className="flex mx-3">
          {props.categories.map((category: any) => (
            <ProductOptionSelected
              onClick={() => setCurrentSelectedCategory(category.id)}
              key={category.id}
              contentValue={category.title}
              isSelected={currentSelectedCategory === category.id}
            />
          ))}
        </div>
        <ListItem products={productsFiltered} />      
        <div className="w-full">
          <div className="bg-gray-400 w-16 h-1 rounded mx-auto"></div>
        </div>
        <div className="px-6 py-2 bg-tahiti-54 hover:bg-tahiti-60 text-white w-40 h-10 rounded-md content-center mt-3 mx-auto">Carregar mais</div>  
        <div className="fixed z-20 p-2 mx-2 mb-1 text-xs bg-tahiti-54 w-14 h-14 rounded-full bottom-0 right-0" >
          <a className=""><Link href="/">Home</Link></a>
        </div>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const products = await getProducts();
  const categories = await getCategories();
  return {
    props: { products, categories },
  };
};


export default Bebidas;

