import type { GetStaticProps, NextPage } from "next";
import { InferGetStaticPropsType } from "next";
import Head from "next/head";

import { getProducts } from "../services/Supabase/Products";

import ListProducts from "../layouts/ListProducts"; 

const Produtos: NextPage = (
  props: InferGetStaticPropsType<typeof getStaticProps>
) => {

  return (
    <>
      <Head>
        <title>Produtos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-shushibar.ico" />
      </Head>
      <nav className="text-3xl font-bold underline h-16 flex flex-row justify-between items-center bg-primary">
        <div>Produtos</div>
      </nav>
      <main className="min-h-screen bg-gray-200 pt-3 justify-center items-center">
          <ListProducts products={props.products} />
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const products = await getProducts();
  return {
    props: { products },
  };
};


export default Produtos;

